# Generated by Django 3.1.4 on 2020-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='lunch')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='image',
            field=models.ImageField(upload_to='lunch'),
        ),
    ]
