# Generated by Django 3.1.4 on 2020-12-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201204_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakFastOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('Alexandria', 'Alexandria'), ('Cairo', 'Cairo'), ('Portsaid', 'Portsaid'), ('Giza', 'Giza'), ('Aswan', 'Aswan')], max_length=25)),
                ('phone', models.IntegerField()),
                ('ordered_at', models.DateTimeField(auto_now=True)),
                ('order_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_order', to='home.breakfast')),
            ],
        ),
    ]
