# Generated by Django 3.1.4 on 2020-12-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_breakfastorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastorders',
            name='order_name_dinner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_order_two', to='home.lunch'),
            preserve_default=False,
        ),
    ]
