# Generated by Django 3.1.4 on 2020-12-05 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_breakfastorders_order_name_dinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastorders',
            name='order_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_order', to='home.breakfast'),
        ),
        migrations.AlterField(
            model_name='breakfastorders',
            name='order_name_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_order_two', to='home.lunch'),
        ),
    ]
