# Generated by Django 3.1.4 on 2020-12-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201205_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfastorders',
            old_name='order_name_dinner',
            new_name='order_name_lunch',
        ),
    ]
