# Generated by Django 3.1.4 on 2020-12-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201205_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakFastOrders',
            new_name='Orders',
        ),
    ]
